import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import "@/styles/globals.css";

import Navbar from "@/components/Navbar";
import Providers from "@/providers";

const font = Archivo({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Ocena modeli aut",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pl">
      <body className={font.className}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
